pronouns:
  max: 3
  valid:
    - 'He'
    - 'Him'
    - 'She'
    - 'Her'
    - 'They'
    - 'Them'
    - 'Star'
    - 'Stars'
    - 'Ey'
    - 'Em'
    - 'Fae'
    - 'Faer'
    - 'We'
    - 'Us'
    - 'It'
    - 'Its'
    - 'Ze'
    - 'Zem'
    - 'Genderfluid'
    - 'Any'
    - 'Ask'
