on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Change Gradle Permissions
        run: chmod +x gradlew
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2.6.0
        with:
          dependency-graph: generate-and-submit
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: build
      - name: Shadow Jar
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: shadowJar
      - name: Deploy to Pterodactyl SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "build/libs/*.jar"
          target: "/plugins/"
          strip_components: 1
          rm: true
          skip_clean: true
          timeout: 120s