name: "Validate Gradle Wrapper"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}+${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
  cancel-in-progress: false

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gradle/wrapper-validation-action@v2.1.1