# This is a basic workflow to help you get started with Actions

name: Gradle Validation

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    - uses: actions/checkout@v3

    # Steps represent a sequence of tasks that will be executed as part of the job
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
